---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  EC2 instance with additional EBS volume set up as an LVM volume.

Parameters:
  VpcIdParameter:
    Description: Launch EC2 instance in this VPC
    Type: AWS::EC2::VPC::Id
  InstanceSubnetIdParameter:
    Description: Launch EC2 instance in this subnet
    Type: AWS::EC2::Subnet::Id
  SshKeyParameter:
    Description: SSH Keypair to login to the instance
    Type: AWS::EC2::KeyPair::KeyName
  InstanceAMIParameter:
    Description: Launch EC2 instance from this AMI
    Type: AWS::EC2::Image::Id
    Default: ami-8ca83fec
  InstanceTypeParameter:
    Description: Confluence EC2 instance family/size, e.g. t2.large
    Type: String
    Default: t2.micro

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from the Internet.
      VpcId: !Ref VpcIdParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            1_pvcreate:
              command: pvcreate /dev/xvdf
            2_vgcreate:
              command: vgcreate vg0 /dev/xvdf
            3_lvcreate:
              command: lvcreate -l 100%FREE -n myapp vg0
            4_mkfs:
              command: mkfs.ext4 /dev/vg0/myapp
            5_mkdir:
              command: mkdir /var/myapp
            6_fstab:
              command: echo "/dev/mapper/vg0-myapp /var/myapp ext4 defaults 0 2" >> /etc/fstab
            7_mount:
              command: mount -a
    Properties:
      BlockDeviceMappings:
        # Create a separate volume
        - DeviceName: /dev/sdf
          Ebs:
            DeleteOnTermination: false
            VolumeSize: 10
      ImageId: !Ref InstanceAMIParameter
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref SshKeyParameter
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref InstanceSubnetIdParameter
      UserData:
        Fn::Base64: !Sub |
         #!/usr/bin/env bash
         set -o errexit
         yum -y update aws-cfn-bootstrap
         /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
         /opt/aws/bin/cfn-signal --exit-code $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}

Outputs:
  EC2InstancePublicIp:
    Description: EC2 instance public IP address
    Value: !GetAtt EC2Instance.PublicIp
